Repository xarray-contrib/xskillscore, pull requests merged in 2021-05, with the labels that each got.

#300 rps category_edges=None
  CHANGELOG.rst
  xskillscore/core/probabilistic.py
  xskillscore/tests/test_probabilistic.py
Labels: enhancement, feature request

#320 Add mypy to pre-commit-config and fix existing typing issues
  .pre-commit-config.yaml
  CHANGELOG.rst
  ci/dev.yml
  docs/source/contributors.rst
  xskillscore/tests/test_mask_skipna.py
  xskillscore/tests/test_probabilistic.py
  xskillscore/tests/test_skipna_functionality.py
Labels: ci, linting

#319 ENH: Renamed mae_test to significance_test and made the function generic
  .pre-commit-config.yaml
  CHANGELOG.rst
  docs/source/api.rst
  docs/source/api/xskillscore.Contingency.accuracy.rst
  docs/source/api/xskillscore.Contingency.bias_score.rst
  docs/source/api/xskillscore.Contingency.correct_negatives.rst
  docs/source/api/xskillscore.Contingency.equit_threat_score.rst
  docs/source/api/xskillscore.Contingency.false_alarm_rate.rst
  docs/source/api/xskillscore.Contingency.false_alarm_ratio.rst
  docs/source/api/xskillscore.Contingency.false_alarms.rst
  docs/source/api/xskillscore.Contingency.gerrity_score.rst
  docs/source/api/xskillscore.Contingency.heidke_score.rst
  docs/source/api/xskillscore.Contingency.hit_rate.rst
  docs/source/api/xskillscore.Contingency.hits.rst
  docs/source/api/xskillscore.Contingency.misses.rst
  docs/source/api/xskillscore.Contingency.odds_ratio.rst
  docs/source/api/xskillscore.Contingency.odds_ratio_skill_score.rst
  docs/source/api/xskillscore.Contingency.peirce_score.rst
  docs/source/api/xskillscore.Contingency.rst
  docs/source/api/xskillscore.Contingency.success_ratio.rst
  docs/source/api/xskillscore.Contingency.table.rst
  docs/source/api/xskillscore.Contingency.threat_score.rst
  docs/source/api/xskillscore.brier_score.rst
  docs/source/api/xskillscore.crps_ensemble.rst
  docs/source/api/xskillscore.crps_gaussian.rst
  docs/source/api/xskillscore.crps_quadrature.rst
  docs/source/api/xskillscore.discrimination.rst
  docs/source/api/xskillscore.effective_sample_size.rst
  docs/source/api/xskillscore.halfwidth_ci_test.rst
  docs/source/api/xskillscore.mae.rst
  docs/source/api/xskillscore.mae_test.rst
  docs/source/api/xskillscore.mape.rst
  docs/source/api/xskillscore.me.rst
  docs/source/api/xskillscore.median_absolute_error.rst
  docs/source/api/xskillscore.mse.rst
  docs/source/api/xskillscore.pearson_r.rst
  docs/source/api/xskillscore.pearson_r_eff_p_value.rst
  docs/source/api/xskillscore.pearson_r_p_value.rst
  docs/source/api/xskillscore.r2.rst
  docs/source/api/xskillscore.rank_histogram.rst
  docs/source/api/xskillscore.reliability.rst
  docs/source/api/xskillscore.rmse.rst
  docs/source/api/xskillscore.roc.rst
  docs/source/api/xskillscore.rps.rst
  docs/source/api/xskillscore.sign_test.rst
  docs/source/api/xskillscore.smape.rst
  docs/source/api/xskillscore.spearman_r.rst
  docs/source/api/xskillscore.spearman_r_eff_p_value.rst
  docs/source/api/xskillscore.spearman_r_p_value.rst
  docs/source/api/xskillscore.threshold_brier_score.rst
  docs/source/conf.py
  docs/source/quick-start.ipynb
  setup.cfg
  xskillscore/__init__.py
  xskillscore/core/comparative.py
  xskillscore/tests/test_comparative.py
Labels: enhancement
